2020-09-02 11:13:15,858 ERROR: Exception on /reset_password_request [POST] [in c:\matea\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\matea\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\matea\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\matea\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\matea\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\matea\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\matea\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\matea\microblog\app\routes.py", line 188, in reset_password_request
    send_password_reset_email(user)
  File "C:\matea\microblog\app\email.py", line 26, in send_password_reset_email
    user=user, token=token))
  File "C:\matea\microblog\app\email.py", line 11, in send_email
    print("mail_port" + app.config['MAIL_USE_SSL'])
KeyError: 'MAIL_USE_SSL'
2020-09-02 11:14:50,034 INFO: Microblog startup [in C:\matea\microblog\app\__init__.py:51]
2020-09-02 11:14:56,883 ERROR: Exception on /reset_password_request [POST] [in c:\matea\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\matea\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\matea\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\matea\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\matea\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\matea\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\matea\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\matea\microblog\app\routes.py", line 188, in reset_password_request
    send_password_reset_email(user)
  File "C:\matea\microblog\app\email.py", line 26, in send_password_reset_email
    user=user, token=token))
  File "C:\matea\microblog\app\email.py", line 11, in send_email
    print("mail_port" + app.config['MAIL_USE_SSL'])
KeyError: 'MAIL_USE_SSL'
2020-09-02 11:15:36,229 INFO: Microblog startup [in C:\matea\microblog\app\__init__.py:51]
2020-09-02 11:15:51,379 ERROR: Exception on /reset_password_request [POST] [in c:\matea\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\matea\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\matea\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\matea\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\matea\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\matea\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\matea\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\matea\microblog\app\routes.py", line 188, in reset_password_request
    send_password_reset_email(user)
  File "C:\matea\microblog\app\email.py", line 27, in send_password_reset_email
    user=user, token=token))
  File "C:\matea\microblog\app\email.py", line 11, in send_email
    print("mail_port" + app.config['MAIL_PORT'])
TypeError: can only concatenate str (not "int") to str
2020-09-02 11:16:52,219 INFO: Microblog startup [in C:\matea\microblog\app\__init__.py:51]
2020-09-02 11:17:01,748 ERROR: Exception on /reset_password_request [POST] [in c:\matea\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\matea\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\matea\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\matea\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\matea\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\matea\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\matea\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\matea\microblog\app\routes.py", line 188, in reset_password_request
    send_password_reset_email(user)
  File "C:\matea\microblog\app\email.py", line 26, in send_password_reset_email
    user=user, token=token))
  File "C:\matea\microblog\app\email.py", line 13, in send_email
    print("mail_use_ssl" + str(app.config['MAIL_USE_SSL']))
KeyError: 'MAIL_USE_SSL'
2020-09-02 11:20:51,406 INFO: Microblog startup [in C:\matea\microblog\app\__init__.py:51]
2020-09-02 11:26:04,538 INFO: Microblog startup [in C:\matea\microblog\app\__init__.py:51]
2020-09-02 11:27:54,860 INFO: Microblog startup [in C:\matea\microblog\app\__init__.py:51]
2020-09-02 11:31:25,790 INFO: Microblog startup [in C:\matea\microblog\app\__init__.py:51]
2020-09-02 11:31:33,981 ERROR: Exception on /reset_password_request [POST] [in c:\matea\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\matea\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\matea\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\matea\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\matea\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\matea\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\matea\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\matea\microblog\app\routes.py", line 188, in reset_password_request
    send_password_reset_email(user)
  File "C:\matea\microblog\app\email.py", line 25, in send_password_reset_email
    user=user, token=token))
  File "C:\matea\microblog\app\email.py", line 14, in send_email
    mail.send(msg)
  File "c:\matea\microblog\venv\lib\site-packages\flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "c:\matea\microblog\venv\lib\site-packages\flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "c:\matea\microblog\venv\lib\site-packages\flask_mail.py", line 163, in configure_host
    host.starttls()
  File "C:\Python\lib\smtplib.py", line 752, in starttls
    "STARTTLS extension not supported by server.")
smtplib.SMTPNotSupportedError: STARTTLS extension not supported by server.
2020-09-02 11:32:42,285 INFO: Microblog startup [in C:\matea\microblog\app\__init__.py:51]
2020-09-02 11:43:35,206 INFO: Microblog startup [in C:\matea\microblog\app\__init__.py:51]
2020-09-02 14:18:19,604 INFO: Microblog startup [in C:\matea\microblog\app\__init__.py:52]
2020-09-02 14:46:03,010 INFO: Microblog startup [in C:\matea\microblog\app\__init__.py:54]
2020-09-02 14:51:26,175 INFO: Microblog startup [in C:\matea\microblog\app\__init__.py:54]
2020-09-02 14:55:45,095 INFO: Microblog startup [in C:\matea\microblog\app\__init__.py:54]
2020-09-02 15:41:12,221 INFO: Microblog startup [in C:\matea\microblog\app\__init__.py:57]
2020-09-03 10:37:40,131 INFO: Microblog startup [in C:\matea\microblog\app\__init__.py:60]
